### ISSUE TITLE
疑似api本身进行了修改导致查询失败

### ISSUE THREAD

**Issue by SanaChitose** [SlightDust/yiqing_HoshinoBot#4]
![图片](https://user-images.githubusercontent.com/102790983/163770003-e9326a83-01c5-4c1f-a549-4ea7df9b3336.png)
浏览器访问api时显示
![图片](https://user-images.githubusercontent.com/102790983/163770091-00bee559-a432-4da4-9bbc-ca72f5eacc25.png)

**Comment by SlightDust** [comment]
已注意到问题，稍等

**Comment by SlightDust** [comment]
似乎是api炸了，数据不完整，之前遇到过这种情况，先再等一等

**Comment by SlightDust** [comment]
扒了一下网页，换了个api，没问题了，pull一下
